#!/bin/bash

# File to store the display manager's service name
DM_SERVICE_FILE="/etc/systemd/system/display-manager.service"
DM_NAME_FILE="/tmp/display_manager_name.tmp"

# Function to get primary dGPU (to check if it's Nvidia)
get_primary_dgpu() {
    lspci | grep VGA | grep -vE 'Intel|AMD' | cut -d " " -f 5
}

# Function to check drm modeset and unload Nvidia modules if needed
unload_nvidia_modules() {
    if grep -q "nvidia-drm.modeset=1" /proc/cmdline; then
        echo "Unloading Nvidia modules..."
        MODULES=("nvidia" "nvidia_modeset" "nvidia_uvm" "nvidia_drm")
        for mod in "${MODULES[@]}"; do
            rmmod "$mod"
        done
    fi
}

# Function to stop the display manager
stop_display_manager() {
    if [ -L "$DM_SERVICE_FILE" ]; then
        DISPLAY_MANAGER=$(systemctl status display-manager | grep -oP 'Loaded:.*?\/\K(.*)(?=\.service)')
        echo "$DISPLAY_MANAGER" > "$DM_NAME_FILE"
        echo "Stopping display manager: $DISPLAY_MANAGER"
        systemctl stop $DISPLAY_MANAGER
    else
        echo "No display manager symlink found."
    fi
}

# Main execution starts here
GPU=$(get_primary_dgpu)
if [ "$GPU" == "NVIDIA" ]; then
    unload_nvidia_modules
fi
stop_display_manager
